[package]
name = "traceroute_rust"
version = "0.1.0"
authors = ["Oliver Layer <olilay@live.de>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
log = "0.4.14"
env_logger = "0.8.3"
pnet = "0.27.2"
dns-lookup = "1.0.6"
rand = "0.8.3"